sudo: required

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy"
  - "pypy3.5"
services:
  - docker
install:
  - pip install pylint yapf -r requirements.txt
script:
  - docker build .
  - pylint **/*.py
  - pytest
  - yapf -d **/*.py
