sudo: required

language: python
python:
  - "3.7"
  - "pypy"
services:
  - docker
install:
  - pip install pylint yapf -r requirements.txt
script:
  - docker build .
  - pylint **/*.py
  - pytest
  - yapf -d **/*.py
