language: python
os: linux
python:
  - "3.7"
services:
  - docker
install:
  - pip install pylint yapf -r requirements.txt
  - gem install mdl
script:
  - docker build -t jraviles/prometheus_speedtest:latest .
  - docker run --rm jraviles/prometheus_speedtest:latest --version
  # Issue #19
  - python -c 'from prometheus_speedtest import prometheus_speedtest as p; p.FLAGS.version = True; p.init()'
  - pylint **/*.py
  - pytest
  - yapf -d **/*.py
  - mdl README.md
